name: Publish

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
            - 'VERSION'
            - '.gitignore'
            - '.github/**'

jobs:
    docker-publish:
        name: Publish to GitHub Container Registry
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Bump version
              uses: remorses/bump-version@js
              id: version
              with:
                  version_file: ./VERSION
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: main
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2.1.0
              with:
                  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2.5.0
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1.14.1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v3.2.0
              with:
                  context: .
                  push: true
                  platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
                  tags: |
                      ghcr.io/danclough/amcrest2mqtt:latest
                      ghcr.io/danclough/amcrest2mqtt:${{ steps.version.outputs.version }}
                  labels: "version=${{ steps.version.outputs.version }}"
